[project]
name = "{{project_name}}"
version = "0.1.0"
java_version = "21"

[dependencies]
"io.javalin:javalin" = "6.1.3"
"org.slf4j:slf4j-simple" = "2.0.12"

[dev-dependencies]
"org.junit.jupiter:junit-jupiter-api" = "5.10.2"
