[project]
name = "javafx_demo"
version = "0.1.0"
java_version = "21"

[dependencies]
"org.openjfx:javafx-base" = "21.0.2:linux"
"org.openjfx:javafx-graphics" = "21.0.2:linux"
"org.openjfx:javafx-controls" = "21.0.2:linux"
"org.openjfx:javafx-fxml" = "21.0.2:linux"

[dev-dependencies]
