use serde::{Deserialize, Serialize};
use std::error::Error;
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct JoltLock {
    pub version: u32,
    #[serde(rename = "package", default)]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub checksum: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
}

impl Default for JoltLock {
    fn default() -> Self {
        Self::new()
    }
}

impl JoltLock {
    pub fn new() -> Self {
        Self {
            version: 1,
            packages: Vec::new(),
        }
    }

    pub fn load_from_file(path: &Path) -> Result<Self, Box<dyn Error + Send + Sync>> {
        let content = fs::read_to_string(path)?;
        let lock: JoltLock = toml::from_str(&content)?;
        Ok(lock)
    }

    pub fn save_to_file(&self, path: &Path) -> Result<(), Box<dyn Error + Send + Sync>> {
        let toml_str = toml::to_string_pretty(self)?;
        let header = "# This file is automatically @generated by Jolt.\n# It is not intended for manual editing.\n\n";
        fs::write(path, format!("{}{}", header, toml_str))?;
        Ok(())
    }

    pub fn add_or_update_package(&mut self, pkg: LockedPackage) {
        if let Some(pos) = self.packages.iter().position(|p| p.name == pkg.name) {
            self.packages[pos] = pkg;
        } else {
            self.packages.push(pkg);
        }
        self.packages.sort_by(|a, b| a.name.cmp(&b.name));
    }

    pub fn remove_package(&mut self, name: &str) -> bool {
        let initial_len = self.packages.len();
        self.packages.retain(|p| p.name != name);
        self.packages.len() < initial_len
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lockfile_serialization() {
        let mut lock = JoltLock::new();
        lock.add_or_update_package(LockedPackage {
            name: "com.google.code.gson:gson".to_string(),
            version: "2.14.0".to_string(),
            checksum: "sha256:abcd1234".to_string(),
            dependencies: vec![],
        });

        let toml_str = toml::to_string(&lock).unwrap();
        let parsed: JoltLock = toml::from_str(&toml_str).unwrap();
        assert_eq!(parsed.packages.len(), 1);
        assert_eq!(parsed.packages[0].name, "com.google.code.gson:gson");
    }
}
