[project]
name = "{{project_name}}"
version = "0.1.0"
java_version = "21"

[dependencies]
"org.springframework.boot:spring-boot-starter-web" = "3.2.3"

[dev-dependencies]
"org.junit.jupiter:junit-jupiter-api" = "5.10.2"
